# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: friend_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x66riend_service.proto\x12\x0e\x66riend_service\"2\n\x10\x41\x64\x64\x46riendRequest\x12\x0e\n\x06peer_1\x18\x01 \x01(\t\x12\x0e\n\x06peer_2\x18\x02 \x01(\t\"$\n\x11\x41\x64\x64\x46riendResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"#\n\x11GetFriendsRequest\x12\x0e\n\x06peer_1\x18\x01 \x01(\t\"%\n\x12GetFriendsResponse\x12\x0f\n\x07\x66riends\x18\x01 \x03(\t\"5\n\x13RemoveFriendRequest\x12\x0e\n\x06peer_1\x18\x01 \x01(\t\x12\x0e\n\x06peer_2\x18\x02 \x01(\t\"\'\n\x14RemoveFriendResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"2\n\x10SetInviteRequest\x12\x0e\n\x06peer_1\x18\x01 \x01(\t\x12\x0e\n\x06peer_2\x18\x02 \x01(\t\"$\n\x11SetInviteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"#\n\x11GetInvitesRequest\x12\x0e\n\x06peer_1\x18\x01 \x01(\t\"%\n\x12GetInvitesResponse\x12\x0f\n\x07invites\x18\x01 \x03(\t\"K\n\x19UpdateInviteStatusRequest\x12\x0e\n\x06peer_1\x18\x01 \x01(\t\x12\x0e\n\x06peer_2\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\x08\"-\n\x1aUpdateInviteStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xb8\x04\n\rFriendService\x12S\n\nadd_friend\x12 .friend_service.AddFriendRequest\x1a!.friend_service.AddFriendResponse\"\x00\x12V\n\x0bget_friends\x12!.friend_service.GetFriendsRequest\x1a\".friend_service.GetFriendsResponse\"\x00\x12\\\n\rremove_friend\x12#.friend_service.RemoveFriendRequest\x1a$.friend_service.RemoveFriendResponse\"\x00\x12S\n\nset_invite\x12 .friend_service.SetInviteRequest\x1a!.friend_service.SetInviteResponse\"\x00\x12V\n\x0bget_invites\x12!.friend_service.GetInvitesRequest\x1a\".friend_service.GetInvitesResponse\"\x00\x12o\n\x14update_invite_status\x12).friend_service.UpdateInviteStatusRequest\x1a*.friend_service.UpdateInviteStatusResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'friend_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ADDFRIENDREQUEST']._serialized_start=40
  _globals['_ADDFRIENDREQUEST']._serialized_end=90
  _globals['_ADDFRIENDRESPONSE']._serialized_start=92
  _globals['_ADDFRIENDRESPONSE']._serialized_end=128
  _globals['_GETFRIENDSREQUEST']._serialized_start=130
  _globals['_GETFRIENDSREQUEST']._serialized_end=165
  _globals['_GETFRIENDSRESPONSE']._serialized_start=167
  _globals['_GETFRIENDSRESPONSE']._serialized_end=204
  _globals['_REMOVEFRIENDREQUEST']._serialized_start=206
  _globals['_REMOVEFRIENDREQUEST']._serialized_end=259
  _globals['_REMOVEFRIENDRESPONSE']._serialized_start=261
  _globals['_REMOVEFRIENDRESPONSE']._serialized_end=300
  _globals['_SETINVITEREQUEST']._serialized_start=302
  _globals['_SETINVITEREQUEST']._serialized_end=352
  _globals['_SETINVITERESPONSE']._serialized_start=354
  _globals['_SETINVITERESPONSE']._serialized_end=390
  _globals['_GETINVITESREQUEST']._serialized_start=392
  _globals['_GETINVITESREQUEST']._serialized_end=427
  _globals['_GETINVITESRESPONSE']._serialized_start=429
  _globals['_GETINVITESRESPONSE']._serialized_end=466
  _globals['_UPDATEINVITESTATUSREQUEST']._serialized_start=468
  _globals['_UPDATEINVITESTATUSREQUEST']._serialized_end=543
  _globals['_UPDATEINVITESTATUSRESPONSE']._serialized_start=545
  _globals['_UPDATEINVITESTATUSRESPONSE']._serialized_end=590
  _globals['_FRIENDSERVICE']._serialized_start=593
  _globals['_FRIENDSERVICE']._serialized_end=1161
# @@protoc_insertion_point(module_scope)
